version: '3.7'
services:
  server:
    build:
      context: ./docker/server
    ports:
      - "4567:4567"
    expose:
      - "4567"
    volumes:
      - type: bind
        source: ./server
        target: /home/server
    restart: always
    depends_on:
      - mongodb
      - nginx
  nginx:
    build:
      context: ./docker/nginx
    restart: always
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
    ports:
      - "443:443"
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  mongodb:
    build:
      context: ./docker/mongodb
    restart: always
    expose:
      - "27017"
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
      - type: volume
        source: mongodb_config
        target: /data/configdb
  certbot:
    image: certbot/certbot
    volumes:
      - type: bind
        source: ./data/certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./data/certbot/www
        target: /var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  mongodb_config:
  mongodb_data:
