version: '3.7'
services:
  server:
    build:
      context: .
    expose:
      - "4567"
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: /Users/sactioswastioyono/eclipse-workspace/NodeBB/build
        target: /usr/src/app/build
      - type: bind
        source: /Users/sactioswastioyono/eclipse-workspace/NodeBB/node_modules
        target: /usr/src/app/node_modules
      - type: bind
        source: /Users/sactioswastioyono/eclipse-workspace/NodeBB/public/uploads
        target: /usr/src/app/public/uploads
    restart: always
    depends_on:
      - mongodb
  mongodb:
    build:
      context: ./install/mongodb
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: /Users/sactioswastioyono/eclipse-workspace/NodeBB_data
        target: /data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=node
      - MONGO_INITDB_ROOT_PASSWORD=node
      - MONGO_INITDB_ROOT_DATABASE=admin
      - MONGO_USERDB_ADMIN_USERNAME=node
      - MONGO_USERDB_ADMIN_PASSWORD=node
      - MONGO_USERDB_ADMIN_DATABASE=nodebb